In [2]:
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from tqdm import tqdm

In [2]:
image_path = "P:/cbir/DATA/wang/image.orig/501.jpg"
image = cv2.imread(image_path)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
sift = cv2.SIFT_create()
key_points, descriptors = sift.detectAndCompute(gray, None)

In [3]:
X = []

step = 8
for des in tqdm(descriptors):
    for i in range(16):
        X.append(des[8*i:8*i+8])

X = np.array(X)

100%|██████████| 1079/1079 [00:00<00:00, 128807.57it/s]


In [4]:
k_means = KMeans(n_clusters=8, init="k-means++", n_init=12)
k_means.fit(X)

KMeans(n_init=12)

In [9]:
predict = k_means.predict(X)
print(predict.shape)
print(predict[:50])

(17264,)
[3 1 4 4 3 1 5 2 3 6 0 2 3 5 4 4 3 3 5 6 3 0 0 0 3 2 0 4 3 3 0 6 3 3 3 3 6
 3 0 0 5 2 0 7 0 2 6 7 1 4]


In [8]:
M = np.zeros((8, 16))
print(M.shape)

(8, 16)


In [11]:
step = 8
for i in range(0, len(predict), 16):
    kp = predict[i:i+16] # a key point includes 16 parts
    for j in range(16):
        M[kp[j], j] += 1 # kp[j]: index of cluster (0 -> 7); j: index of part (0 -> 15)
print(M.shape)
print(M) 

(8, 16)
[[146. 378. 340. 126. 220. 594. 732. 164. 156. 646. 658. 168. 132. 328.
  346. 138.]
 [260. 202. 156. 120. 356. 340.  76. 200. 148.  88. 250. 286. 156. 144.
  210. 226.]
 [128. 148. 208. 228. 186.  92. 258. 286. 320. 356.  94. 170. 300. 250.
  174. 126.]
 [906. 488. 460. 968. 560. 106. 102. 696. 580.  94. 114. 702. 858. 482.
  504. 946.]
 [260. 352. 272. 156. 292. 204. 114. 130. 170. 116. 204. 298. 146. 250.
  338. 332.]
 [104. 216. 290. 114. 100. 498. 434. 158. 132. 436. 548. 126. 132. 256.
  234.  94.]
 [136. 208. 306. 272. 156.  78. 200. 244. 332. 170.  62. 134. 254. 304.
  226. 172.]
 [218. 166. 126. 174. 288. 246. 242. 280. 320. 252. 228. 274. 180. 144.
  126. 124.]]


In [15]:
M_flat = M.flatten()
print(M_flat.shape)
print(M_flat)

(128,)
[146. 378. 340. 126. 220. 594. 732. 164. 156. 646. 658. 168. 132. 328.
 346. 138. 260. 202. 156. 120. 356. 340.  76. 200. 148.  88. 250. 286.
 156. 144. 210. 226. 128. 148. 208. 228. 186.  92. 258. 286. 320. 356.
  94. 170. 300. 250. 174. 126. 906. 488. 460. 968. 560. 106. 102. 696.
 580.  94. 114. 702. 858. 482. 504. 946. 260. 352. 272. 156. 292. 204.
 114. 130. 170. 116. 204. 298. 146. 250. 338. 332. 104. 216. 290. 114.
 100. 498. 434. 158. 132. 436. 548. 126. 132. 256. 234.  94. 136. 208.
 306. 272. 156.  78. 200. 244. 332. 170.  62. 134. 254. 304. 226. 172.
 218. 166. 126. 174. 288. 246. 242. 280. 320. 252. 228. 274. 180. 144.
 126. 124.]


In [3]:
image_path = "P:/cbir/DATA/wang/image.orig/501.jpg"
image = cv2.imread(image_path)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

sift = cv2.SIFT_create()
key_points, descriptors = sift.detectAndCompute(gray, None)

v_hat = np.zeros((len(key_points), 8))

for i in range(len(key_points)):
    for j in range(8):
        for k in range(16):
            v_hat[i, j] += descriptors[i, 8*k+j]
print(v_hat.shape)
print(v_hat)

(1079, 8)
[[ 776.  661.  617. ...  443.  273.  393.]
 [1043.  435.  235. ...  317.  491.  655.]
 [ 992.  419.   70. ...  583.  450.  412.]
 ...
 [ 526.  279.  529. ...  213.  276.  672.]
 [ 786.  435.  329. ...  325.  835.  682.]
 [ 836.  680.  788. ...  371.  168.  327.]]


In [4]:
k_means = KMeans(n_clusters=16)
k_means.fit(v_hat)

KMeans(n_clusters=16)

In [7]:
predict = k_means.predict(v_hat)
print(predict.shape)
print(predict[:100])

(1079,)
[12  2  9  7 11  1  7  0 10 15 10  2  7 12  1 15  0 11  2  4  1  1 15  6
  1 13 14  7  8  1  7 12  0 15  1  6 12 13  7 15  7 10  7 15 15  1  6  0
 11 15  1  7 15 13 12  6 11  2  0 10 11 13  7  1 15 12 12  2 12  7 15  1
 14  1 14  6  7 15 11 15 15 12  7  2  9  7 11  0  3  6 10  1  7  1 11  4
  6 11 11  4]


In [8]:
G = np.zeros((16,))
print(G.shape)
print(G)

(16,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
for y_hat in predict:
    G[y_hat] += 1

In [10]:
print(G.shape)
print(G)

(16,)
[80. 86. 65. 37. 89. 60. 65. 87. 45. 33. 64. 79. 73. 71. 59. 86.]
